require("nvim_conf")
require("keybinds_conf")
require("dashboard_conf")
require("fugitive_conf")
require("telescope_conf")
require("colorscheme_conf")
require("treesitter_conf")
require("scrollbar_conf")
require("cmp_conf")
require("mason_conf")
require("neotree_conf")
require("lualine_conf")
require("terminal_conf")
require("mini_conf")
require("gitsigns_conf")
require("aerial_conf")

-- These plugins don't require any specific configs
require('glow').setup()
require("fidget").setup()
